# Generated by Django 5.0.3 on 2024-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_header",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="report_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="site_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
